version = 5.5.0
archive_dir = /etc/letsencrypt/archive/genesisdao.tech
cert = /etc/letsencrypt/live/genesisdao.tech/cert.pem
privkey = /etc/letsencrypt/live/genesisdao.tech/privkey.pem
chain = /etc/letsencrypt/live/genesisdao.tech/chain.pem
fullchain = /etc/letsencrypt/live/genesisdao.tech/fullchain.pem
[renewalparams]
account = ec22385543cd21c0d5b0b8305a9c77fc
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
[acme_renewal_info]
ari_retry_after = 2026-05-02T18:58:16
